/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class services_CppServiceDirectory */

#ifndef _Included_services_CppServiceDirectory
#define _Included_services_CppServiceDirectory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     services_CppServiceDirectory
 * Method:    callNativeMethod
 * Signature: (I[Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_services_CppServiceDirectory_callNativeMethod
  (JNIEnv *, jobject, jint, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
