/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class services_CppServiceDirectory */

#ifndef _Included_services_CppServiceDirectory
#define _Included_services_CppServiceDirectory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     services_CppServiceDirectory
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_services_CppServiceDirectory_nativePrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
